# Generated by Django 2.2 on 2019-07-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_new_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('username', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
    ]
